# version: "3.8"

# services:
#   frontend:
#     depends_on:
#       - backend
#     build: ./frontend
#     ports:
#       - 3000:3000

#   backend:
#     depends_on:
#       - db
#     build: ./backend
#     ports:
#       - 3001:3001
#     environment:
#       DB_URL: mongodb://db/vidly
#     command: ./docker-entrypoint.sh

#   db:
#     image: mongo:4.0-xenial
#     ports:
#       - 27017:27017
#     volumes:
#       - vidly:/data/db

# volumes:
#   vidly:

version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=supersecret
  mongo-express:
    image: mongo-express
    ports:
      - 8083:8083
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
